---
abstract: 'break up numbers into arbitrary denominations'
author:
  - 'Zoffix Znet <cpan@zoffix.com>'
build_requires:
  Test::Deep: 0
  Test::More: 0
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Number-Denominal
requires:
  Carp: 0
  Exporter: 0
  List::ToHumanString: 1.002
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/zoffixznet/Number-Denominal/issues
  repository: git://github.com/zoffixznet/Number-Denominal.git
version: v1.106
